Write-Host "Removing previously set TCP rules..."
Remove-NetFirewallRule -DisplayName "PORT 137 INBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 137 OUTBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 138 INBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 138 OUTBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 139 INBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 139 OUTBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 445 INBOUND TCP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 445 OUTBOUND TCP CLOSED"

Write-Host "Removing previously set UDP rules..."
Remove-NetFirewallRule -DisplayName "PORT 137 INBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 137 OUTBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 138 INBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 138 OUTBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 139 INBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 139 OUTBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 445 INBOUND UDP CLOSED"
Remove-NetFirewallRule -DisplayName "PORT 445 OUTBOUND UDP CLOSED"

Write-Host "Done!"